// Generated from openapi/openapi.yaml. Do not edit.
export const GAME_MANAGE_KIT_CONTRACT_VERSION = "2.0.0";

export const GameManageKitPath = {
  AdminLogin: "/v1/admin/auth/login",
  AdminLogout: "/v1/admin/auth/session",
  AdminReauthenticate: "/v1/admin/auth/reauthenticate",
  BanAccount: "/v1/games/{gameId}/admin/accounts/{userId}/ban",
  BootstrapAdmin: "/v1/admin/bootstrap",
  CreateAdminGame: "/v1/admin/games",
  CreateAdminGameServer: "/v1/admin/games/{gameId}/servers",
  CreateAdminMachineIdentity: "/v1/admin/machine-identities",
  DevLogin: "/v1/games/{gameId}/sessions/dev",
  GetAdminAccount: "/v1/games/{gameId}/admin/accounts/{userId}",
  GetAdminBootstrapStatus: "/v1/admin/bootstrap",
  GetAdminGameDirectorySettings: "/v1/admin/games/{gameId}/directory-settings",
  GetAdminGameIntegration: "/v1/admin/games/{gameId}/integration",
  GetAdminMachineSecretRotationStatus: "/v1/admin/machine-identities/{identityId}/secret-rotations/{operationId}",
  GetAdminSession: "/v1/admin/auth/session",
  HasCharacter: "/v1/games/{gameId}/internal/characters/{userId}/{serverId}",
  ListAdminConfigAudit: "/v1/admin/config-audit",
  ListAdminGames: "/v1/admin/games",
  ListAdminGameServers: "/v1/admin/games/{gameId}/servers",
  ListAdminMachineIdentities: "/v1/admin/machine-identities",
  ListAreas: "/v1/games/{gameId}/areas",
  ListClientGames: "/v1/games",
  Livez: "/livez",
  Metrics: "/metrics",
  Readyz: "/readyz",
  RegisterCharacter: "/v1/games/{gameId}/internal/characters/{userId}/{serverId}",
  ReplaceAdminWechatAppSecret: "/v1/admin/games/{gameId}/secrets/wechat-app-secret",
  RevokeAccount: "/v1/games/{gameId}/admin/accounts/{userId}/revoke",
  RevokeAdminMachineSecret: "/v1/admin/machine-identities/{identityId}/secret-versions/{version}/revoke",
  RotateAdminMachineSecret: "/v1/admin/machine-identities/{identityId}/secret-rotations",
  UpdateAdminGame: "/v1/admin/games/{gameId}",
  UpdateAdminGameDirectorySettings: "/v1/admin/games/{gameId}/directory-settings",
  UpdateAdminGameIntegration: "/v1/admin/games/{gameId}/integration",
  UpdateAdminGameServer: "/v1/admin/games/{gameId}/servers/{serverId}",
  UpdateAdminMachineIdentity: "/v1/admin/machine-identities/{identityId}",
  VerifySession: "/v1/games/{gameId}/internal/sessions/verify",
  Version: "/version",
  WxLogin: "/v1/games/{gameId}/sessions/wechat",
} as const;

export const GameManageKitMethod = {
  AdminLogin: "POST",
  AdminLogout: "DELETE",
  AdminReauthenticate: "POST",
  BanAccount: "POST",
  BootstrapAdmin: "POST",
  CreateAdminGame: "POST",
  CreateAdminGameServer: "POST",
  CreateAdminMachineIdentity: "POST",
  DevLogin: "POST",
  GetAdminAccount: "GET",
  GetAdminBootstrapStatus: "GET",
  GetAdminGameDirectorySettings: "GET",
  GetAdminGameIntegration: "GET",
  GetAdminMachineSecretRotationStatus: "GET",
  GetAdminSession: "GET",
  HasCharacter: "GET",
  ListAdminConfigAudit: "GET",
  ListAdminGames: "GET",
  ListAdminGameServers: "GET",
  ListAdminMachineIdentities: "GET",
  ListAreas: "GET",
  ListClientGames: "GET",
  Livez: "GET",
  Metrics: "GET",
  Readyz: "GET",
  RegisterCharacter: "PUT",
  ReplaceAdminWechatAppSecret: "PUT",
  RevokeAccount: "POST",
  RevokeAdminMachineSecret: "POST",
  RotateAdminMachineSecret: "POST",
  UpdateAdminGame: "PATCH",
  UpdateAdminGameDirectorySettings: "PATCH",
  UpdateAdminGameIntegration: "PATCH",
  UpdateAdminGameServer: "PATCH",
  UpdateAdminMachineIdentity: "PATCH",
  VerifySession: "POST",
  Version: "GET",
  WxLogin: "POST",
} as const;
