// Generated from openapi/openapi.yaml. Do not edit.
export const GAME_MANAGE_KIT_CONTRACT_VERSION = "1.2.0";

export const GameManageKitPath = {
  AdminLogin: "/v1/admin/auth/login",
  AdminLogout: "/v1/admin/auth/session",
  BanAccount: "/v1/games/{gameId}/admin/accounts/{userId}/ban",
  CreateAdminGame: "/v1/admin/games",
  CreateAdminGameServer: "/v1/admin/games/{gameId}/servers",
  DevLogin: "/v1/games/{gameId}/sessions/dev",
  GetAdminAccount: "/v1/games/{gameId}/admin/accounts/{userId}",
  GetAdminSession: "/v1/admin/auth/session",
  HasCharacter: "/v1/games/{gameId}/internal/characters/{userId}/{serverId}",
  ListAdminGames: "/v1/admin/games",
  ListAdminGameServers: "/v1/admin/games/{gameId}/servers",
  ListAreas: "/v1/games/{gameId}/areas",
  ListClientGames: "/v1/games",
  Livez: "/livez",
  Metrics: "/metrics",
  Readyz: "/readyz",
  RegisterCharacter: "/v1/games/{gameId}/internal/characters/{userId}/{serverId}",
  RevokeAccount: "/v1/games/{gameId}/admin/accounts/{userId}/revoke",
  UpdateAdminGame: "/v1/admin/games/{gameId}",
  UpdateAdminGameServer: "/v1/admin/games/{gameId}/servers/{serverId}",
  VerifySession: "/v1/games/{gameId}/internal/sessions/verify",
  Version: "/version",
  WxLogin: "/v1/games/{gameId}/sessions/wechat",
} as const;

export const GameManageKitMethod = {
  AdminLogin: "POST",
  AdminLogout: "DELETE",
  BanAccount: "POST",
  CreateAdminGame: "POST",
  CreateAdminGameServer: "POST",
  DevLogin: "POST",
  GetAdminAccount: "GET",
  GetAdminSession: "GET",
  HasCharacter: "GET",
  ListAdminGames: "GET",
  ListAdminGameServers: "GET",
  ListAreas: "GET",
  ListClientGames: "GET",
  Livez: "GET",
  Metrics: "GET",
  Readyz: "GET",
  RegisterCharacter: "PUT",
  RevokeAccount: "POST",
  UpdateAdminGame: "PATCH",
  UpdateAdminGameServer: "PATCH",
  VerifySession: "POST",
  Version: "GET",
  WxLogin: "POST",
} as const;
